# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_auto_20170303_0957'),
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='sessionuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessionuser', to='login_reg.User'),
        ),
    ]
